const APP_API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;

const WAREHOUSE_API_ENDPOINT = APP_API_ENDPOINT + "/warehouses";
const CUSTOMER_API_ENDPOINT = APP_API_ENDPOINT + "/customers";
const SUPPLIER_API_ENDPOINT = APP_API_ENDPOINT + "/suppliers";
const PRODUCT_CATEGORY_API_ENDPOINT = APP_API_ENDPOINT + "/product-categories";
const PRODUCT_API_ENDPOINT = APP_API_ENDPOINT + "/products";
export {
	APP_API_ENDPOINT,
	WAREHOUSE_API_ENDPOINT,
	CUSTOMER_API_ENDPOINT,
	SUPPLIER_API_ENDPOINT,
	PRODUCT_CATEGORY_API_ENDPOINT,
	PRODUCT_API_ENDPOINT,
};
