const APP_API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;

const WAREHOUSE_API_ENDPOINT = APP_API_ENDPOINT + "/warehouses";
const CUSTOMER_API_ENDPOINT = APP_API_ENDPOINT + "/customers";
const SUPPLIER_API_ENDPOINT = APP_API_ENDPOINT + "/suppliers";
const PRODUCT_CATEGORY_API_ENDPOINT = APP_API_ENDPOINT + "/product-categories";
const PRODUCT_API_ENDPOINT = APP_API_ENDPOINT + "/products";
const PRODUCT_PRICE_API_ENDPOINT = APP_API_ENDPOINT + "/product-prices";
const INVENTORY_ITEM_API_ENDPOINT = APP_API_ENDPOINT + "/inventory-items";
const MATERIAL_ORDER_API_ENDPOINT = APP_API_ENDPOINT + "/material-orders";
const LOT_API_ENDPOINT = APP_API_ENDPOINT + "/lots";

export {
	APP_API_ENDPOINT,
	WAREHOUSE_API_ENDPOINT,
	CUSTOMER_API_ENDPOINT,
	SUPPLIER_API_ENDPOINT,
	PRODUCT_CATEGORY_API_ENDPOINT,
	PRODUCT_API_ENDPOINT,
	PRODUCT_PRICE_API_ENDPOINT,
	INVENTORY_ITEM_API_ENDPOINT,
	MATERIAL_ORDER_API_ENDPOINT,
	LOT_API_ENDPOINT,
};
