const ESTATUS = {
	CREATED: "CREATED",
	PROCESSING: "PROCESSING",
	DELIVERED: "DELIVERED",
	COMPLETED: "COMPLETED",
};

const MATERIAL_ORDER_STATUS = {
	CREATED: "CREATED",
	APPROVED: "APPROVED",
	IN_TRANSIT: "IN_TRANSIT",
	DELIVERED: "DELIVERED",
	CANCELLED: "CANCELLED",
};

export { ESTATUS, MATERIAL_ORDER_STATUS };
