const APP_API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT;

const WAREHOUSE_API_ENDPOINT = APP_API_ENDPOINT + "/warehouses";
const CUSTOMER_API_ENDPOINT = APP_API_ENDPOINT + "/customers";
const SUPPLIER_API_ENDPOINT = APP_API_ENDPOINT + "/suppliers";

export default APP_API_ENDPOINT;
export { WAREHOUSE_API_ENDPOINT, CUSTOMER_API_ENDPOINT, SUPPLIER_API_ENDPOINT };
